# DawsOS Observability Stack
# Purpose: Jaeger, Prometheus, Grafana for monitoring
# Updated: 2025-10-26
# Usage: docker compose -f docker-compose.yml -f docker-compose.observability.yml up -d

services:
  # ============================================================================
  # Jaeger: Distributed Tracing
  # ============================================================================
  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: dawsos-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "5775:5775/udp"    # Accept zipkin.thrift over compact thrift protocol
      - "6831:6831/udp"    # Accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp"    # Accept jaeger.thrift over binary thrift protocol
      - "5778:5778"        # Serve configs
      - "16686:16686"      # Serve frontend (UI)
      - "14268:14268"      # Accept jaeger.thrift directly from clients
      - "14250:14250"      # Accept model.proto
      - "9411:9411"        # Zipkin compatible endpoint
    networks:
      - dawsos-network
    restart: unless-stopped

  # ============================================================================
  # Prometheus: Metrics Collection
  # ============================================================================
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: dawsos-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
    networks:
      - dawsos-network
    restart: unless-stopped

  # ============================================================================
  # Alertmanager: Alert Routing
  # ============================================================================
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: dawsos-alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    volumes:
      - ./observability/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    networks:
      - dawsos-network
    restart: unless-stopped

  # ============================================================================
  # Grafana: Dashboards & Visualization
  # ============================================================================
  grafana:
    image: grafana/grafana:10.1.0
    container_name: dawsos-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - dawsos-network
    restart: unless-stopped

# ============================================================================
# Networks (extends docker-compose.yml)
# ============================================================================
networks:
  dawsos-network:
    external: true

# ============================================================================
# Volumes
# ============================================================================
volumes:
  prometheus_data:
    driver: local
  alertmanager_data:
    driver: local
  grafana_data:
    driver: local
