# Prometheus Configuration
# Purpose: Scrape targets and alerting rules
# Updated: 2025-10-26

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dawsos'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alerting rules
rule_files:
  - '/etc/prometheus/alerts.yml'

# Scrape configurations
scrape_configs:
  # DawsOS Backend API
  - job_name: 'dawsos-backend'
    static_configs:
      - targets:
          - 'backend:8000'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  # PostgreSQL (if pg_exporter is added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets:
  #         - 'postgres-exporter:9187'

  # Redis (if redis_exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets:
  #         - 'redis-exporter:9121'
