# Agent Configuration
# Defines agent properties and relationships

agents:
  # Orchestrator Agents
  graph_mind:
    type: orchestrator
    description: Living intelligence that manages the knowledge graph
    vibe: omniscient
    sub_agents:
      - connection_vibes
      - strength_feeler
    priority: high

  claude:
    type: interface
    description: Main conversational interface
    vibe: friendly and curious
    sub_agents:
      - intent_parser
      - response_crafter
      - memory_keeper
    priority: high

  # Builder Agents
  code_monkey:
    type: builder
    description: Writes actual code
    vibe: eager to code
    max_complexity: 50  # lines per function
    sub_agents:
      - function_writer
      - import_manager
      - docstring_bot
    priority: medium

  structure_bot:
    type: organizer
    description: Maintains file organization
    vibe: organized
    sub_agents:
      - file_creator
      - folder_organizer
    priority: medium

  refactor_elf:
    type: maintainer
    description: Keeps code simple
    vibe: minimalist
    complexity_limit: 50
    file_limit: 200
    sub_agents:
      - complexity_scanner
      - splitter
    priority: low

  # Data Agents
  data_harvester:
    type: data
    description: Fetches data from all sources
    vibe: hungry for data
    sources:
      - fred
      - market
      - news
      - crypto
    priority: high

  data_digester:
    type: processor
    description: Converts data to graph nodes
    vibe: thoughtful
    sub_agents:
      - node_maker
      - metadata_adder
      - confidence_rater
    priority: high

  # Knowledge Agents
  relationship_hunter:
    type: analyzer
    description: Finds connections between nodes
    vibe: curious
    max_depth: 3
    priority: medium

  pattern_spotter:
    type: analyzer
    description: Identifies patterns
    vibe: observant
    sub_agents:
      - sequence_tracker
      - cycle_finder
      - anomaly_detector
    min_occurrences: 3
    priority: medium

  forecast_dreamer:
    type: predictor
    description: Makes predictions
    vibe: prophetic
    sub_agents:
      - path_tracer
      - signal_aggregator
      - confidence_calculator
    priority: medium

  # Workflow Agents
  workflow_recorder:
    type: learner
    description: Records successful patterns
    vibe: studious
    sub_agents:
      - step_logger
      - success_judge
      - template_extractor
    min_pattern_count: 3
    priority: low

  workflow_player:
    type: executor
    description: Replays workflows
    vibe: efficient
    sub_agents:
      - context_matcher
      - parameter_filler
      - executor
    priority: medium

# Agent Relationships
relationships:
  claude_delegates_to:
    - graph_mind
    - data_harvester
    - code_monkey
    - pattern_spotter

  graph_mind_uses:
    - data_digester
    - relationship_hunter
    - forecast_dreamer

  data_harvester_feeds:
    - data_digester

  pattern_spotter_informs:
    - workflow_recorder
    - forecast_dreamer

  workflow_recorder_enables:
    - workflow_player

# Execution Order
execution_priority:
  1: [claude, graph_mind]
  2: [data_harvester, data_digester]
  3: [relationship_hunter, pattern_spotter]
  4: [forecast_dreamer]
  5: [code_monkey, structure_bot]
  6: [workflow_recorder]
  7: [refactor_elf]