# DawsOS Test Stack
# Purpose: Isolated environment for running tests
# Updated: 2025-10-22
# Usage: docker compose -f docker-compose.test.yml up -d

services:
  # ============================================================================
  # Test Database: PostgreSQL + TimescaleDB
  # ============================================================================
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: dawsos-test-postgres
    environment:
      POSTGRES_USER: dawsos_test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: dawsos_test
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster tests
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dawsos_test"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - test-network

  # ============================================================================
  # Test Redis
  # ============================================================================
  redis:
    image: redis:7-alpine
    container_name: dawsos-test-redis
    command: redis-server --save ""  # Disable persistence for tests
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    tmpfs:
      - /data  # Use tmpfs for faster tests
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
