[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4A9EFF"
backgroundColor = "#0A0E27"
secondaryBackgroundColor = "#0F1629"
textColor = "#E8E9F3"
font = "sans serif"

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
